### ISSUE TITLE
Google error "id_token must be passed in or set as part of setAccessToken"

### ISSUE THREAD

**Issue by markguinn** [notthatbad/silverstripe-rest-api-oauth#2]
Have you gotten this to work? What are you doing on the client? I'm using HelloJS and passing in the access_token it gives.

**Comment by 1blankz7** [comment]
I have written a simple example for HelloJS: https://github.com/notthatbad/silverstripe-rest-api-oauth/wiki/client-example

Do you have this error at the moment?

The current develop branch crashes with some errors on TravisCI. After fixing the issue I will create a new version.

**Comment by markguinn** [comment]
Nope. The changes from your most recent PR are to fix this error. Our client code is very similar to your example.
